#!/bin/sh -e

## Copyright 2019-2020 Vagrant Cascadian <vagrant@debian.org>
## Copyright 2022 Leonid Gasheev aka <The-going> <48602507+The-going@users.noreply.github.com>

## This program comes with ABSOLUTELY NO WARRANTY; for details see
## COPYING.  This is free software, and you are welcome to
## redistribute it under the terms of the GNU GPL, version 2 or any
## later version; see COPYING for details.

# sync .dtb files into /boot to simplify installations on systems with
# a split /boot partition.  To use, install this file into
# /etc/kernel/postinst.d/zz-sync-dtb and mark it as executable.

# This original file is contained in the u-boot-menu package
# in the documentation section as an example. The file has been changed
# taking into account the specifics of Armbian in that the dtb files
# can be either in a separate package or contained directly
# in the kernel package.

version="$1"

command -v rsync >/dev/null 2>&1 || exit 0

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: sync-dtb: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

dtbdir="/usr/lib/linux-image-${version}"
dstdir="/boot/dtb-${version}"

# If a separate dtb package was previously installed and
# the destination directory already exists. Nothing needs to be done.
if [ -d "$dstdir" ]; then
	exit 0
fi

if [ -d "${dtbdir}" ]; then
	echo >&2 "W: sync-dtb: syncing ${dtbdir} to ${dstdir}"
	mkdir -p "${dstdir}"
	rsync -a "${dtbdir}/." "${dstdir}/."
else
	echo >&2 "W: sync-dtb: ${dtbdir} NOT PRESENT"
fi
